#!usr/bin/env python
# -*- coding: utf-8 -*-

# 匹配优先级：\{(.+(\n.+){2,6}\])},
# 建议搭配“选择所有匹配项”和String Manipulation插件进行修改

DIR_KEYWORD_MAP = {
    "博丽灵梦": [
        0,  # 出场次数优先级，越小越靠前
        "boli", "lingmeng", "bllm", "bl", "lm",  # 中文拼音：姓、名、姓名首字母、姓首字母、名首字母
        "hakurei", "reimu",  # 罗马音：姓、名
        "hb", "hongbai", "wunv", "wn", "miko", "rim", "ywn", "swwn", "chengguan", "cg", "cssrm",  # 昵称、相关外号
        "zhujue", "zj", "yuandian", "yd", "jiejie", "jj",  # cp
    ],
    "雾雨魔理沙": [
        1,
        "wuyu", "molisha", "wymls", "wy", "mls",
        "kirisame", "marisa",
        "hb", "heibai", "witch", "mrs", "ss", "shasha", "yongchang", "yc", "mns", "jfxnh", "mpz", "shasha",
        "tk", "zhujue", "zj",
    ],
    "十六夜咲夜": [
        2,
        "shiliuye", "xiaoye", "slyxy", "sly", "xy",
        "izayoi", "sakuya",
        "pad", "padz", "maid", "dio", "world", "sky", "np", "xyy",
        "meixiao", "mx",
    ],
    "魂魄妖梦": [
        3,
        "hunpo", "yaomeng", "hpym", "hp", "ym",
        "konpaku", "youmu",
        "yomeng", "yo", "mashu", "umeng", "um", "myon", "yooooo", "qljs",
        "youming",
    ],
    "八云紫": [
        4,
        "bayunzi", "bayun", "zi", "byz", "by", "z",
        "yukari", "yakumo",
        "bba", "zima", "zimei", "zm", "ltp", "ykl", "shiqi", "sq",
        "qiannian", "qn", "jiejie", "jj",
    ],
    "蕾米莉亚": [
        5,
        "leimiliya", "sikaleite", "lmlysklt", "lmly", "sklt",
        "remilia", "scarlet",
        "daxiaojie", "dxj", "leimi", "lm", "xxg", "weiyan", "sister", "btdf",
        "jiejie", "jj", "jiemei", "beide", "bd",
    ],
    "西行寺幽幽子": [
        6,
        "xixingsi", "youyouzi", "xxsyyz", "xxs", "yyz",
        "saigyouji", "yuyuko", "sgj", "yyk",
        "uuz", "chihuo", "dww", "yy",
        "qn", "qiannian", "ym", "youming",
    ],
    "射命丸文": [
        7,
        "shemingwan", "wen", "smww", "smw", "w",
        "aya", "wenwen", "ww", "xgjz", "gzw", "ayayaya",
        "wenhua", "wh",
    ],
    "琪露诺": [
        8,
        "qilunuo", "qln", "q",
        "cirno", "chiruno",
        "baka", "bendan", "jiu", "xj", "nine", "yousei", "yaojing",
        "yjz", "yj",
    ],
    "八云蓝": [
        9,
        "bayunlan", "byl", "by", "l",
        "yakumo", "ran",
        "slth", "lanma", "lm", "hl", "huli", "jwh",
    ],
    "伊吹萃香": [
        10,
        "yichui", "cuixiang", "yccx", "yc", "cx",
        "ibuki", "suika",
        "melon", "xigua", "xg", "oni", "gui", "glls", "gm", "zx", "sik",
    ],
    "东风谷早苗": [
        11,
        "dongfenggu", "zaomiao", "dfgzm", "dfg", "zm",
        "kochiya", "kotiya", "sanae",
        "m", "miaoye", "my", "miko", "fengzhu", "fz", "she", "caotian", "ct", "xrs", "mm", "jdxzm",
        "wunv", "wn",
    ],
    "八坂神奈子": [
        12,
        "baban", "shennaizi", "bbsnz", "bb", "snz",
        "yasaka", "kanako",
        "shenma", "sm", "yuzhu", "ss", "fs", "feishen", "bba", "mj",
    ],
    "帕秋莉": [
        13,
        "paqiuli", "nuoleiji", "pqlnlj", "pql", "nlj",
        "patchouli", "knowledge",
        "muq", "mq", "paqi", "pq", "ghx",
    ],
    "橙": [
        14,
        "cheng", "ch", "c", "chen",
        "bayun", "by", "chengmiao", "cm", "cheeeeeeeeen",
    ],
    "爱丽丝": [
        15,
        "ailisi", "mageteluoyide", "als", "mgtlyd", "am",
        "alice", "margatroid",
        "mls", "mrs", "weizhentian", "wzt", "xiaoai", "xa", "renou", "ro",
        "yongchang", "yc",
    ],
    "铃仙": [
        16,
        "lingxian", "youtanhuayuan", "youtanhua", "yinfan", "lx", "ythy", "yth", "yf", "lyy",
        "reisen", "udongein", "inaba", "rs",
        "wudong", "udon", "wd", "tutu", "shoutu", "st", "yzlb", "zyt",
    ],
    "洩矢诹访子": [
        17,
        "xieshi", "zoufangzi", "xszfz", "zfz",
        "moriya", "suwako", "swk",
        "qingwazi", "qingwa", "qwz", "qw", "mo", "xym", "zf",
        "feishen", "fs",
    ],
    "八意永琳": [
        18,
        "bayi", "yonglin", "byyl", "by", "yl",
        "eirin", "yagokoro", "er",
        "tasuke", "helpme", "tsk", "shijiang", "pzj", "yztn", "jsc", "bba",
        "yongyuan", "yy",
    ],
    "藤原妹红": [
        19,
        "tengyuan", "meihong", "tymh", "ty", "mh",
        "Huziwara", "Mokou", "hzwr", "mk",
        "yemen", "ymh", "mokotan", "mogutan", "mgt", "bsn",
        "busi", "bsz", "bs", "zhulin", "zl",
    ],
    "河城荷取": [
        20,
        "hecheng", "hequ", 'hchq', "hc", "hq"
        'kawasiro", "nitori',
        "hetong", "ht", "huanggua", "hg", "htzg", "lbn",
    ],
    "因幡帝": [
        21,
        "yinfan", "di", "tianwei", "yfd", "yftw", "yf", "d", "tw",
        "tewi", "inaba",
        "didi", "fuheitu", "fuhei", "xld", "fh", "htz", "tutu",
    ],
    "莉莉霍瓦特": [
        22,
        "lili", "huowate", "llhwt", "hwt",
        "lilywhite", "lily", "white",
        "lilibai", "lilihei", "llb", "b", "llh", "bll", "czyj", "jcj",
    ],
    "蓬莱山辉夜": [
        23,
        "penglaishan", "huiye", "plshy", "pls", "hy",
        "houraisan", "kaguya",
        "neet", "hyj",
        "bs", "busi", "bsz", "yongyuan", "yy",
    ],
    "小野塚小町": [
        24,
        "xiaoyezhong", "xiaoting", "xyzxt", "xyz", "xt",
        "onozuka", "onoduka", "komachi",
        "sishen", "ss", "ruting", "rt",
    ],
    "比那名居天子": [
        25,
        "binamingju", "tianzi", "bnmtz", "bn", "tz",
        "hinanawi", "tenshi",
        "tln", "mz", "mzi", "momoko", "mmk", "taozi",
    ],
    "圣白莲": [
        26,
        "sheng", "bailian", "sbl", "s", "bl",
        "hiziri", "hijiri", "byakuren",
        "lianma", "lm", "sjdhmz", "mfs", "motor", "mt", "mls", "bba",
    ],
    "云居一轮": [
        27,
        "yunju", "yilun", "yjyl", "yj", "yl",
        "kumoi", "ichirin",
        "unzan", "ys",
    ],
    "二岩猯藏": [
        28,
        "eryan", "tuanzang", "eytz", "ey", "tz",
        "hutatsuiwa", "futatsuiwa", "mamizou",
        "dalizi", "dlz", "ruizang", "rz", "limao",
    ],
    "上白泽慧音": [
        29,
        "shangbaize", "huiyin", "sbzhy", "sbz", "hy",
        "kamishirasawa", "keine",
        "laoshi", "ls", "xbzhy", "baize", "bz",
        "zhulin", "zl",
    ],
    "丰聪耳神子": [
        30,
        "fengconger", "shenzi", "fcesz", "fce", "sz",
        "toyosatomimi", "miko", "tnm",
        "taizi", "tz", "sdtz", "esz", "bba",
    ],
    "宇佐见莲子": [
        31,
        "yuzuojian", "lianzi", "yzjlz", "yzj", "lz",
        "usami", "renko",
        "mifeng", "mf", "dxs",
    ],
    "玛艾露贝莉·赫恩": [
        32,
        "maailubeili", "heen", "malblhe", "malbl",
        "maribel", "hearn",
        "meili", "ml", "mifeng", "mf", "dxs", "byz",
    ],
    "红美铃": [
        33,
        "hong", "meiling", "hml", "h", "ml",
        "hon", "meirin",
        "hsf",  "zhongguo", "zg", "mw",
        "sjmxjc", "meixiao", "mx",
    ],
    "米斯蒂娅·萝蕾拉": [
        34,
        "misidiya", "luoleila", "msdylll", "msdy", "lll", "msd",
        "mystia", "lorelei",
        "lbn", "xcg", "cuigu", "msq", "nsjy", "bksyn", "yq", "yeque",
    ],
    "秋穰子": [
        35,
        "qiu", "rangzi", "qrz", "q", "rz",
        "aki", "minoriko",
        "hongshu", "qjm", "mm", "qxz", "xz",
    ],
    "火焰猫燐": [
        36,
        "huoyanmao", "lin", "hyml", "hym", "l",
        "kaenbyou", "rin",
        "alin", "al", "maoche", "mc", "hc",
        "chongwu", "cwz", "cw",
    ],
    "灵乌路空": [
        37,
        "lingwulu", "kong", "lwlk", "lwl", "k",
        "reiuji", "utsuho",
        "akong", "ak", "gaoda", "gd", "hedan", "hd", "h", "six", "liu", "wuya", "wy",
        "chongwu", "cwz", "cw",
    ],
    "古明地恋": [
        38,
        "gumingdi", "lian", "gmld", "gmd", "l",
        "komeiji", "koishi",
        "lianlian", "ll", "xiaoshi", "xst", "gmdsx", "wuyisi", "wys", "dmx", "tezg", "mzxs",
        "meimei", "mm", "juelian", "jl", "ddjm",
    ],
    "多多良小伞": [
        39,
        "duoduoliang", "xiaosan", "ddlxs", "ddl", "xs",
        "tatara", "kogasa",
        "xsj", "tangsan", "ts", "tsyg",
    ],
    "斯塔萨菲雅": [
        40,
        "sita", "safeiya", "stsfy", "st", "sfy",
        "star", "sapphire",
        "syj", "yj",
    ],
    "桑尼米尔克": [
        41,
        "sangni", "mierke", "snmek", "sn", "mek",
        "sunny", "milk",
        "syj", "yj", "gmnn",
    ],
    "露娜切露德": [
        42,
        "luna", "qielude", "lnqld", "ln", "qld",
        "child",
        "syj", "yj", "lnc",
    ],
    "四季映姬": [
        43,
        "sijiyingji", "yemoxiannadu", "sjyj", "siji", "sj", "yingji", "yj", "ymxnd", "ymsnd",
        "shikieiki", "yamaxanadu", "shiki", "eiki",
        "ylw", "yanluo", "yl", "sjdr", "snt",
    ],
    "秋静叶": [
        44,
        "qiu", "jingye", "qjy", "q", "jy",
        "aki", "sizuha",
        "jiejie", "jj", "qjm", "qj",
    ],
    "键山雏": [
        45,
        "jianshan", "chu", "jsc", "js", "c",
        "kagiyama", "hina",
        "zhuanzhuan", "zhuan", "zz", "eshen", "es", "xln", "srn",
    ],
    "星熊勇仪": [
        46,
        "xingxiong", "yongyi", "xxyy", "xx", "yy",
        "hoshiguma", "yuugi",
        "hys", "oni", "gui",
    ],
    "古明地觉": [
        47,
        "gumingdi", "jue", "gmdj", "gmd", "j",
        "komeiji", "satori",
        "xiaowu", "wu", "five", "xwu", "xwll",
        "jiejie", "jj", "juelian", "jl", "ddjm",
    ],
    "娜兹玲": [
        48,
        "naziling", "nzl", "ncl",
        "nazrin", "n",
        "laoshu", "ls", "xb",
    ],
    "芙兰朵露": [
        49,
        "fulanduolu", "sikaleite", "fldl", "sklt",
        "flandre", "scarlet", "fs",
        "erxiaojie", "exj", "ermei", "em", "fulan", "fl", "lll", "xhscjd", "xxg",
        "meimei", "mm", "beide", "bd",
    ],
    "蕾蒂": [
        50,
        "leidi", "huowateluoke", "ldhwtlk", "ld", "hwtlk",
        "letty", "whiterock",
        "jiuma", "heimu", "xn",
    ],
}
